### ISSUE TITLE
Problem with utility versioning API (v:doc)

### ISSUE THREAD

**Issue by dovikos** [eXist-db/xquery-versioning-module#1]
Hello guys,
I'm no sure, but I think there's a problem with the **utility versioning API** (`versioning.xqm`, `namespace=http://exist-db.org/versioning`).

I found, to my sense, errors with the `v:doc` function, and therefore `v:annotate` and `v:diff`.
Let say I have a base document, and then I:

1.  insert an element in a first revision (_rev=1_),
2. then another in a second revision (_rev=2_),
3. then another in the last revision (_rev=3_).

When I check the result of my document at revision 1 with `v:doc`, I see my first inserted element; that's OK.
When I check the result of my document at revision 2 with `v:doc`, I see my second element inserted, but the **first element inserted in revision 1 appears twice** = KO.
When I do the same at revision 3, I have **three times** my first insert element, **twice** the second one and then the once the third one = KO.

From my point of view, `v:doc` is applying **too many patches** and **doesn't reflect** the document at a point.

The other consequence is that my document (after modifications) and the result with `v:doc` at the last revision applied to this document are **different**!

Thanks for reading
Dovikos

**Comment by dizzzz** [comment]
@dovikos please could you fill-in the template?

**Comment by dovikos** [comment]
@dizzzz Thanks for answer. 
I'm sorry, I'm new to Github. I don't find any template in the project...

**Comment by dizzzz** [comment]
ah sorry, it is indeed not there; it is in the main project :-) 
it helps if you fill in this form: https://github.com/eXist-db/exist/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by dovikos** [comment]
### What is the problem
Function `v:doc` of the **utility versioning API** (`versioning.xqm`, `namespace=http://exist-db.org/versioning`) return is wrong. Therefore `v:annotate` and `v:diff` are also wrong.
All diffs from base to target revision are applied to the base document. Let's assume n is the target revision, the modification of the first revision is applied n times, the modification of the second revision is applied n-1 times and so on.

### What did you expect
I expect only the target revision diff to be applied and to get the representation of the document at this revision.

### Describe how to reproduce or add a test
Let say I have a base document. Then I insert an element in a first revision (rev=1), then another in a second revision (rev=2), then another in the last revision (rev=3).
When I check the result of my document at revision 1 with `v:doc`, I see my first inserted element; that's OK.
When I check the result of my document at revision 2 with `v:doc`, I see my second element inserted, but the **first element inserted in revision 1 appears twice** = KO.
When I do the same at revision 3, I have **three times** my first insert element, **twice** the second one and then the once the third one = KO.

From my point of view, `v:doc` **doesn't reflect** the document at a point.

The other consequence is that my document (after modifications) is **different** from the result of `v:doc` at the last revision applied to this document!

### Context information
- eXist-db version = 2.2
- Java version = Java8u121
- Operating system = Windows 7
- 64 bit
- No custom changes

**Comment by adamretter** [comment]
Thanks for reporting. I just fixed it and uploaded version 1.1.2
