### ISSUE TITLE
Not all details and versions seem to be stored after xQuery update operations

### ISSUE THREAD

**Issue by lguariento** [eXist-db/xquery-versioning-module#11]
I have enabled the versioning by installing the module available in package manager and adding

```
<collection xmlns="http://exist-db.org/collection-config/1.0">
    <index>
        <fulltext default="none" attributes="no">
        </fulltext>
    </index>
    <triggers>
        <trigger event="create,delete,update"
            class="org.exist.versioning.VersioningTrigger">
            <parameter name="overwrite" value="no"/>
        </trigger>
    </triggers>
</collection>
```

to `/db/system/config/db/collection.xconf`.

**Issue 1**

When a user calls a `update insert` xquery (via an html form) a new version file is created under the `system/versions` folder with information about added items. For `update delete`, though, it creates a version file with something like:

```
<v:version xmlns:v="http://exist-db.org/versioning">
    <v:properties>
        <v:document>file.xml</v:document>
        <v:user>user</v:user>
        <v:date>2018-02-27T11:05:52.999Z</v:date>
        <v:revision>44</v:revision>
    </v:properties>
    <v:diff>
        <v:delete ref="3.5.2.2.666"/>
    </v:diff>
</v:version>
```

Is it possible to have details about *what* has been deleted?

**Issue 2**

Also I noticed that version 43 hasn't been created. I only have version 42 and 44. I have several of these gaps. Why is it so?

**Issue 3**

Finally, this query in eXide:

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:history(doc("/db/apps/app-ct/data/indices/pedb.xml"))
```

Returns all the versions (with the above-mentioned gaps) I see in my system folder. Nevertheless, something like:

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:versions(doc("/db/apps/app-ct/data/indices/pedb.xml"))
```

only returns the first 10 versions. This is a weird behaviour. I've cleared the browser's cache several times. What is happening?

**Comment by adamretter** [comment]
In response:

## Issue 1
You are not meant to access the information in system directly. Instead you can use `v:diff` to see what has changed.

## Issue 2
I think the revision number is likely per-Collection not per-Document.

## Issue 3
`v:versions` looks like it should return all versions for a doc. If it is not, that would likely be a bug that needs to be debugged. Perhaps you could take a look at the XQuery source code of `v:versions` (https://github.com/eXist-db/xquery-versioning-module/blob/master/src/main/xquery/versioning.xqm#L50) and run it line by line to see what seems to be the problem on your system...

**Comment by lguariento** [comment]
Hi Adam,

thanks.

## Issue 1

Yes, in fact that's what I did (and discovered that dubious error message, see https://github.com/eXist-db/exist/issues/1756). `v:diff`, as far as I can see, prints out more or less what I can see in the files. For instance, a `v:diff` for version 44 as per example below:

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:diff(doc('db/apps/app-ct/data/mydoc.xml'), 44)
```

outputs:

```
<v:version xmlns:v="http://exist-db.org/versioning">
<v:properties>
<v:document>/db/system/versions/temp/mydoc.xml</v:document>
<v:user>myuser</v:user>
<v:date>2018-03-01T16:15:21.053Z</v:date>
<v:revision/>
</v:properties>
<v:diff>
<v:delete ref="1.5.2.2.666"/>
<v:insert ref="1">
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?><?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
</v:insert>
</v:diff>
</v:version>
```

It was a simple deletion in one node (not in the header), and all I get is `<v:delete ref="1.5.2.2.666"/>` and the xml declaration, which I didn't touch. Still, no info about what I deleted.

## Issue 2

Yes, I worked it out precisely in the moment you published your reply! Am I the only one in thinking this is counter-intuitive and that it would make much more sense if the version numbers were file-by-file and not collection-wide? Something like mydoc.xml.24 with the following revision at mydoc.xml.97 looks a bit weird to me and less helpful than a consecutive numeration.

## Issue 3

I'll do some tests and report back.

### Update

@adamretter , sorry, could you please help me in debugging this? In eXide, the xQuery

```
xquery version "3.0";
module namespace v = "http://exist-db.org/versioning";

declare variable $v:VERSIONS_COLLECTION := "/db/system/versions";

declare function v:versions($doc as node()) as element(v:version)* {
    let $doc := doc('db/apps/myapp/mydoc.xml')
    let $collection := util:collection-name($doc)
    let $doc-name := util:document-name($doc)
    let $version-collection := concat($v:VERSIONS_COLLECTION, $collection)
    for $version in collection($version-collection)/v:version[v:properties/v:document = $doc-name]
    order by xs:long($version/v:properties/v:revision) ascending
    return
$version
};
```

doesn't return anything. Surely I'm overlooking something embarrassingly trivial. How can I run it 'line by line', as you suggest?

**Comment by lguariento** [comment]
Sorry @adamretter, that was a stupid oversight. I didn't realise that eXide paginates by default to 10 items. So I had to hit the '>>' arrows, then I saw the rest of the results. How can one control this kind of behaviour? Perhaps it might be a good thing to make this more obvious for dumb users like myself. But other than that, that was definitely my oversight - sorry for the trouble.

Still, if you could advise about issues 1 and 2 that would be grand.

**Comment by lguariento** [comment]
Hi @adamretter , I'm still getting unexpected behaviour. For instance, a

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:history(doc("/db/apps/app-ct/data/myfile.xml"))
```
returns

```
<v:history xmlns:v="http://exist-db.org/versioning">
<v:document>/db/apps/app-ct/data/myfile.xml</v:document>
    <v:revisions>
      <v:revision rev="230">
          <v:date>2018-03-03T15:08:40.125Z</v:date>
          <v:user>User1</v:user>
     </v:revision>
     <v:revision rev="233">
         <v:date>2018-03-11T18:25:34.229Z</v:date>
         <v:user>User2</v:user>
     </v:revision>
    <v:revision rev="277">
        <v:date>2018-03-15T15:49:20.111Z</v:date>
        <v:user>admin</v:user>
    </v:revision>
[...etc]
</v:revisions>
</v:history>
```
Now,

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:diff(doc("/db/apps/app-ct/data/indices/pldb.xml"), 233)
```
or 230, or 277, or any version, always returns the same content of the last diff file. What am I doing wrong?
