### ISSUE TITLE
 Function v:diff() is not defined in namespace 'http://exist-db.org/versioning'

### ISSUE THREAD

**Issue by lguariento** [eXist-db/xquery-versioning-module#12]
Hello,

I have eXist 4.0.0 running on CentOS 7 and I'm using the versioning module offered in the package manager. I can successfully use v.history or v:revisions. Nevertheless, if I type something like

```
xquery version "3.1";

import module namespace v="http://exist-db.org/versioning";
v:diff(doc("/db/apps/app-ct/data/indices/pedb.xml"))
```
into eXide, it complains that `Function v:diff() is not defined in namespace 'http://exist-db.org/versioning`. Do I need to install something additional?

**Comment by dizzzz** [comment]
is this the exact errormessage? afaik diff() required two parameters....

**Comment by lguariento** [comment]
Sorry, that was dumb of me. I was editing a previous query; yes, I added the second parameter (which didn't copy-paste here), and for some reasons eXide live preview was not 'reading' it. It works fine now, sorry again for the bother and thanks for our swift reply!

PS: I do think, though, that that error message does not represent the actual issue of not adding a second parameter.

**Comment by dizzzz** [comment]
I actually expected indeed a different error message; where it could say 'something' about parameter cardinality 1 vs 2

**Comment by lguariento** [comment]
Yep, that would be much more useful. I have tried again with one argument, it still complains about the function not being defined in the namespace.

**Comment by dizzzz** [comment]
this is what I see when I supply 1 parameter to a 2 parameter function:

![clipboard01](https://user-images.githubusercontent.com/1700062/36730953-795871d4-1bc9-11e8-9696-765d31166bc3.png)


I expected the same like feedback in your case....

**Comment by lguariento** [comment]
Definitely. Instead:

![diff](https://user-images.githubusercontent.com/10143842/36731233-07d12648-1bc2-11e8-9227-d5a3a08e534d.jpg)

**Comment by dizzzz** [comment]
how strange..... and inconvenient as the feedback I had would guide you into the right direction.

lLease could you file an issue for the 'core' eXist-db repo, with both examples (including images) ? I think we might want to address this... :-)

**Comment by lguariento** [comment]
Sure, will do that later!
