### ISSUE TITLE
classcast BrokerPool.PROPERTY_DATA_DIR

### ISSUE THREAD

**Issue by eduarddrenth** [eXist-db/xquery-versioning-module#2]
In exist 3.1 this property is a Path.

on line 463 of VersioningTrigger this fails:

final String dataDir = (String) pool.getConfiguration().getProperty(BrokerPool.PROPERTY_DATA_DIR);

**Comment by adamretter** [comment]
Thanks for reporting. I just fixed it and uploaded version 1.1.1
