### ISSUE TITLE
Exception in VersioningTrigger

### ISSUE THREAD

**Issue by dovikos** [eXist-db/xquery-versioning-module#3]
### What is the problem
The xquery-versioning-module failed to store diffs.
I think the problem is the same as #2.

### What did you expect
When I update a file (which collection is configured for versioning) , I expected that the versioning module:
- would create a base file in the /db/system/versions collection if not exists = success;
- would create a diff between current and base file = this failed;

### Describe how to reproduce or add a test
Build **xquery-versioning-module-1.1.jar**.
Copy it to `$EXIST_HOME/lib/user` of your **eXist 3.1** installation.
Register the versioning module in `conf.xml`, as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md).
Start eXist.
Configure a collection `{your-collection}` with the versioning trigger registered (see [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.3)).
Update a file in this collection, and see that no diff was created in `/db/system/versions/{your-collection}` (only the `.base` file is created).

Here is the found stacktrace when I configured logs on the `org.exist.versioning` package. (I put in bold relevant informations to me) :

> 017-03-18 14:48:08,546 [qtp665565246-28] ERROR (VersioningTrigger.java [after]:410) - Caught exception in VersioningTrigger: sun.nio.fs.WindowsPath cannot be cast to java.lang.String 
> **java.lang.ClassCastException: sun.nio.fs.WindowsPath cannot be cast to java.lang.String**
> 	at **org.exist.versioning.VersioningTrigger.newRevision(VersioningTrigger.java:463)** ~[xquery-versioning-module-1.1.jar:?]
> 	at org.exist.versioning.VersioningTrigger.after(VersioningTrigger.java:341) ~[xquery-versioning-module-1.1.jar:?]
> 	at org.exist.versioning.VersioningTrigger.afterUpdateDocument(VersioningTrigger.java:577) ~[xquery-versioning-module-1.1.jar:?]
> 	at org.exist.collections.triggers.DocumentTriggers.afterUpdateDocument(DocumentTriggers.java:254) ~[exist.jar:3.1.0]
> 	at org.exist.collections.MutableCollection.storeXMLInternal(MutableCollection.java:1264) ~[exist.jar:3.1.0]
> 	at org.exist.collections.MutableCollection.store(MutableCollection.java:1150) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.lambda$storeXMLResource$13(LocalCollection.java:587) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.lambda$null$22(LocalCollection.java:729) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.function.LocalXmldbCollectionFunction.apply(LocalXmldbCollectionFunction.java:48) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.AbstractLocal.lambda$with$6(AbstractLocal.java:172) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.AbstractLocal.lambda$null$4(AbstractLocal.java:118) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.function.LocalXmldbFunction.apply(LocalXmldbFunction.java:46) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.AbstractLocal.withDb(AbstractLocal.java:195) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.AbstractLocal.lambda$modify$5(AbstractLocal.java:118) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.lambda$modify$23(LocalCollection.java:727) ~[exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.storeXMLResource(LocalCollection.java:552) [exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.storeResource(LocalCollection.java:502) [exist.jar:3.1.0]
> 	at org.exist.xmldb.LocalCollection.storeResource(LocalCollection.java:491) [exist.jar:3.1.0]
> 	at org.exist.xquery.functions.xmldb.XMLDBStore.evalWithCollection(XMLDBStore.java:243) [exist.jar:3.1.0]
> 	at org.exist.xquery.functions.xmldb.XMLDBAbstractCollectionManipulator.eval(XMLDBAbstractCollectionManipulator.java:174) [exist.jar:3.1.0]
> 	at org.exist.xquery.BasicFunction.eval(BasicFunction.java:74) [exist.jar:3.1.0]
> 	at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:41) [exist.jar:3.1.0]
> 	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:100) [exist.jar:3.1.0]
> 	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:3.1.0]
> 	at org.exist.xquery.ConditionalExpression.eval(ConditionalExpression.java:102) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:99) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:3.1.0]
> 	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:3.1.0]
> 	at org.exist.xquery.TryCatchExpression.eval(TryCatchExpression.java:142) [exist.jar:3.1.0]
> 	at org.exist.xquery.DebuggableExpression.eval(DebuggableExpression.java:58) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.LetExpr.eval(LetExpr.java:111) [exist.jar:3.1.0]
> 	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:3.1.0]
> 	at org.exist.xquery.PathExpr.eval(PathExpr.java:276) [exist.jar:3.1.0]
> 	at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71) [exist.jar:3.1.0]
> 	at org.exist.xquery.XQuery.execute(XQuery.java:253) [exist.jar:3.1.0]
> 	at org.exist.xquery.XQuery.execute(XQuery.java:185) [exist.jar:3.1.0]
> 	at org.exist.http.RESTServer.executeXQuery(RESTServer.java:1506) [exist-optional.jar:3.1.0]
> 	at org.exist.http.RESTServer.checkForXQueryTarget(RESTServer.java:1203) [exist-optional.jar:3.1.0]
> 	at org.exist.http.RESTServer.doPut(RESTServer.java:1004) [exist-optional.jar:3.1.0]
> 	at org.exist.http.servlets.EXistServlet.doPut(EXistServlet.java:128) [exist-optional.jar:3.1.0]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) [servlet-api-3.1.jar:3.1.0]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:159) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.exist.http.urlrewrite.Forward.doRewrite(Forward.java:50) [exist-optional.jar:3.1.0]
> 	at org.exist.http.urlrewrite.XQueryURLRewrite.doRewrite(XQueryURLRewrite.java:545) [exist-optional.jar:3.1.0]
> 	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:349) [exist-optional.jar:3.1.0]
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [servlet-api-3.1.jar:3.1.0]
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171) [betterform-exist-5.1-SNAPSHOT-20160615.jar:?]
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524) [jetty-security-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.9.v20160517.jar:9.3.9.v20160517]
> 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

### Context information
- eXist-db version + Git Revision hash: eXist-db 3.1 /  [`c679cd8`](https://github.com/eXist-db/exist/commit/c679cd8a1fb991a2c9f10b8196d30cd9cf864792) 
- xquery-versioning-module version + Git Revision hash: 1.1 / 1920f555987dc649b6c3c8a11db9d6fc973bd97a
- Java version: Java8u121
- Operating system: Windows 7
- 64 bit
- Custom changes: in `conf.xml`, I added the following line in the `<builtin-modules>` element as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md):
`<module uri="http://exist-db.org/xquery/versioning" class="org.exist.versioning.xquery.VersioningModule"/>`
I also added the utility API module: `<module uri="http://exist-db.org/versioning" src="resource:org/exist/versioning/xquery/versioning.xqm"/>`
I also enabled the serialized filter as explained [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.4).

**Comment by adamretter** [comment]
Thanks for reporting. I just fixed it and uploaded version 1.1.1
