### ISSUE TITLE
"VersioningFilter" is not applicable

### ISSUE THREAD

**Issue by dovikos** [eXist-db/xquery-versioning-module#6]
### What is the problem
The **`VersioningFilter`** is not applicable.

### What did you expect
With the serialization filter enabled, I expect to see the added metadata attributes (like `v:revision`, `v:key`)  when accessing a document, as described [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.7).

### Describe how to reproduce or add a test

- Compile the `xquery-versioning-module` project as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md) (with the Java 8 and Maven 3 requirement).

- Copy the built `target/xquery-versioning-module-1.1.2-exist.jar` into `$EXIST_HOME/lib/user`.

- In `$EXIST_HOME/conf.xml`, add the following line in the `<builtin-modules>` element as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md) (paragraph **Direct Installation into eXist-db (.jar)**):
`<module uri="http://exist-db.org/xquery/versioning" class="org.exist.versioning.xquery.VersioningModule"/>`.

- In `$EXIST_HOME/conf.xml`, enable the `VersioningFilter` by adding the following line in the `<serializer>` element as explained [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.4):
`<custom-filter class="org.exist.versioning.VersioningFilter"/>`.

- Restart eXist-db.

- Configure a collection with the versioning trigger registered (see [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.3)).

- Access to document in this collection to see that versioning metadata attributes (`v:revision`, `v:key`, `v:path`) are not added as they are supposed to be.

### Context information
- eXist-db version + Git Revision hash: eXist-db 3.1 /  [`c679cd8`](https://github.com/eXist-db/exist/commit/c679cd8a1fb991a2c9f10b8196d30cd9cf864792) 
- xquery-versioning-module version + Git Revision hash: 1.1.2 / 1c1bfba3b6a89760a1903b47236e0da4ec4847de
- Java version: Java8u121
- Operating system: Windows 7
- 64 bit
- Custom changes: in `conf.xml`, I added the following line in the `<builtin-modules>` element as explained [here](https://github.com/eXist-db/xquery-versioning-module/blob/master/README.md):
`<module uri="http://exist-db.org/xquery/versioning" class="org.exist.versioning.xquery.VersioningModule"/>`
I also enabled the serialized filter `VersioningFilter` as explained [here](http://exist-db.org/exist/apps/doc/versioning.xml#D2.2.4.4).

**Comment by dovikos** [comment]
I found in the sources that the function `boolean triggerRegistered(Class<?> triggerClass)` in [`CollectionConfiguration`](https://github.com/eXist-db/exist/blob/develop/src/org/exist/collections/CollectionConfiguration.java) indicating if a collection got a trigger registered is incomplete:
```java
//TODO: code
public boolean triggerRegistered(Class<?> triggerClass) {
	return false;
}
```

Even setting return value to **`true`** has no effect (I still can't get metadata attributes `v:rev`, `v:key`, ..., when opening a document).

**Comment by adamretter** [comment]
I have sent a PR to eXist which fixes this issue here: https://github.com/eXist-db/exist/pull/1404

Before the bugfix I would see serialized output like:

```xml
<thing>
	<and>
		<other/>
	</and>
</thing>
```

after the bugfix I get the correct serialized output:

```xml
<thing xmlns:v="http://exist-db.org/versioning" v:revision="2" v:key="15b67fb03fb2" v:path="/db/vers/thing1.xml">
	<and>
		<other/>
	</and>
</thing>
```
